### ISSUE TITLE
Error: Invalid or corrupt jarfile target/choerodon-tool-liquibase.jar

### ISSUE THREAD

**Issue by jalynxing** [choerodon/iam-service#1]
I get the error `Error: Invalid or corrupt jarfile target/choerodon-tool-liquibase.jar` after executing the command `sh init-local-database.sh`. I don't know how to solve it.

**Comment by devane001** [comment]
This is due to incomplete download of `choerodon-tool-liquibase.jar`. 

You can download the correct version of  `choerodon-tool-liquibase.jar` from https://oss.sonatype.org/content/groups/public/io/choerodon/choerodon-tool-liquibase/.

Replace the local file and executing the command `sh init-local-database.sh` again.

**Comment by twtyjvkg** [comment]
初始化脚本报错
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'iam_service.fd_organization' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_172]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.41.jar!/:5.1.41]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_172]
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.14.jar!/:na]
        at com.sun.proxy.$Proxy56.executeQuery(Unknown Source) ~[na:na]
        at io.choerodon.liquibase.excel.DbAdaptor.checkExists(DbAdaptor.java:169) ~[choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.excel.DbAdaptor.processTableRow(DbAdaptor.java:111) ~[choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.excel.ExcelDataLoader.processTable(ExcelDataLoader.java:202) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.excel.ExcelDataLoader.processTableCopy(ExcelDataLoader.java:101) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.excel.ExcelDataLoader.processData(ExcelDataLoader.java:77) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.excel.ExcelDataLoader.execute(ExcelDataLoader.java:291) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.load(LiquibaseExecutor.java:262) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.simpleExec(LiquibaseExecutor.java:199) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.runToDb(LiquibaseExecutor.java:164) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.execute(LiquibaseExecutor.java:84) [choerodon-liquibase-0.6.1.RELEASE.jar!/:0.6.1.RELEASE]
        at io.choerodon.liquibase.StartupRunner.run(StartupRunner.java:21) [classes!/:0.6.1.RELEASE]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:747) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
        at io.choerodon.liquibase.LiquibaseTools.main(LiquibaseTools.java:19) [classes!/:0.6.1.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_172]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_172]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [choerodon-tool-liquibase.jar:0.6.1.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [choerodon-tool-liquibase.jar:0.6.1.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [choerodon-tool-liquibase.jar:0.6.1.RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [choerodon-tool-liquibase.jar:0.6.1.RELEASE]
```

**Comment by superlee007** [comment]
你好，用的是master分支的代码吗，还有choerodon-tool-liquibase用的是那个版本

**Comment by twtyjvkg** [comment]
对，使用的master分支，choerodon-tool-liquibase使用的0.6.1.RELEASE

**Comment by superlee007** [comment]
修改下数据库配置，表名小写
```
[mysqld]
lower_case_table_names=1
character_set_server=utf8
max_connections=500
```
