### ISSUE TITLE
修改logo图片异常

### ISSUE THREAD

**Issue by muercy** [choerodon/iam-service#6]
你好，异常如下：
`exception info io.choerodon.core.exception.CommonException: error.setting.logo.save.failure
	at io.choerodon.iam.app.service.impl.SystemSettingServiceImpl.uploadSystemLogo(SystemSettingServiceImpl.java:66)
	at io.choerodon.iam.api.controller.v1.SystemSettingController.uploadLogo(SystemSettingController.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)`

对应代码异常堆栈没有输出，不方便排错，帮忙看下，谢谢！

**Comment by superlee007** [comment]
什么版本？主分支的吗

**Comment by muercy** [comment]
0.14.1   谢谢。建议把异常堆栈打印到日志。
